django_web_profiler/urls.py
from django.conf.urls import url
from .views import (index, records_list, device_records_list)

app_name = 'django_web_profiler'

urlpatterns = [
    # url(r'^home/$','home'),
    url(r'^$', index, name="index"),
    url(r'^records/list/(?P<record_id>[-\w]+)/$', records_list, name='records_list'),

    url(r'^device-records-list/$', device_records_list, name='device_records_list'),

]

django_web_profiler/models.py
from django.db import models


class ProfileLog(models.Model):
    """Captures overall statistics about a single test run."""
    name = models.CharField(max_length=255, blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)
    hostname = models.CharField(max_length=255, blank=True, null=True)

    total_requests = models.IntegerField(blank=True, null=True)
    avg_time = models.FloatField(blank=True, null=True)
    total_time = models.FloatField(blank=True, null=True)
    avg_cpu_time = models.FloatField(blank=True, null=True)
    total_user_cpu_time = models.FloatField(blank=True, null=True)
    total_system_cpu_time = models.FloatField(blank=True, null=True)

    avg_sql_time = models.FloatField(blank=True, null=True)
    total_sql_time = models.FloatField(blank=True, null=True)
    avg_sql_queries = models.FloatField(blank=True, null=True)
    total_sql_queries = models.IntegerField(blank=True, null=True)

    avg_cache_hits = models.FloatField(blank=True, null=True)
    total_cache_hits = models.IntegerField(blank=True, null=True)
    avg_cache_misses = models.FloatField(blank=True, null=True)
    total_cache_misses = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return u'Test Rume from %s to %s' % (self.start_time, self.end_time)


class ProfileLogRecord(models.Model):
    """Captures statistics for individual requests."""
    timestamp = models.DateTimeField(auto_now_add=True)
    profile_log = models.ForeignKey(
        ProfileLog, blank=True, null=True, related_name='profile_log', on_delete=models.CASCADE)

    request_path = models.CharField(max_length=255)
    ip_address = models.CharField(max_length=255)
    device = models.CharField(max_length=255)
    arguments = models.TextField(default='')
    kw_arguments = models.TextField(default='')

    # Timer stats
    timer_utime = models.FloatField(blank=True, null=True)
    timer_stime = models.FloatField(blank=True, null=True)
    timer_cputime = models.FloatField(blank=True, null=True)
    timer_total = models.FloatField(blank=True, null=True)
    timer_vcsw = models.IntegerField(blank=True, null=True)
    timer_ivcsw = models.IntegerField(blank=True, null=True)

    # Sql stats
    sql_num_queries = models.IntegerField(blank=True, null=True)
    sql_time = models.FloatField(blank=True, null=True)
    sql_queries = models.FloatField(blank=True, null=True)

    # Cache stats
    cache_num_calls = models.IntegerField(blank=True, null=True)
    cache_time = models.FloatField(blank=True, null=True)
    cache_hits = models.IntegerField(blank=True, null=True)
    cache_misses = models.IntegerField(blank=True, null=True)
    cache_sets = models.IntegerField(blank=True, null=True)
    cache_gets = models.IntegerField(blank=True, null=True)
    cache_get_many = models.IntegerField(blank=True, null=True)
    cache_deletes = models.IntegerField(blank=True, null=True)
    cache_calls = models.TextField(default='')

    def __unicode__(self):
        return u'DebugLogRecord from %s' % self.timestamp

django_web_profiler/views.py
import math

from django.shortcuts import render, get_object_or_404
from .models import ProfileLog, ProfileLogRecord
from django.db.models import Q


# Create your views here.
def index(request):
    profile_logs = ProfileLog.objects.filter().order_by('-start_time')
    return render(request, 'profiler_base.html', {'profile_logs': profile_logs})


def get_prev_after_pages_count(page, no_pages):
    prev_page = page - 1
    if prev_page == 1:
        previous_page = prev_page
    else:
        previous_page = prev_page - 1
    if page == 1:
        prev_page = page
        previous_page = page

    if page == no_pages:
        aft_page = no_pages
        after_page = no_pages
    else:
        aft_page = page + 1
        if aft_page == no_pages:
            after_page = no_pages
        else:
            after_page = aft_page + 1
    return prev_page, previous_page, aft_page, after_page


def records_list(request, record_id):
    profile_logs = ProfileLog.objects.filter().order_by('-start_time')
    profile_log = get_object_or_404(ProfileLog, id=record_id)
    profile_log_records = ProfileLogRecord.objects.filter(
        profile_log_id=record_id)
    if request.POST.get("search"):
        profile_log_records = profile_log_records.filter(Q(request_path__icontains=request.POST.get(
            "search")) | Q(ip_address__icontains=request.POST.get("search")))
    if request.POST.get("queries"):
        profile_log_records = profile_log_records.filter(Q(sql_queries__lte=request.POST.get(
            "queries")) | Q(timer_utime__lte=request.POST.get("queries")))

    no_of_jobs = profile_log_records.count()
    items_per_page = 10
    no_pages = int(math.ceil(float(no_of_jobs) / items_per_page))
    page = request.POST.get('page')
    if request.method == 'GET':
        page = request.GET.get('page')
    try:
        if int(page) > 0:
            if int(page) > (no_pages + 2):
                page = 1
            else:
                page = int(page)
        else:
            page = 1
    except:
        page = 1

    profile_log_records = profile_log_records[
        (page - 1) * items_per_page:page * items_per_page]
    prev_page, previous_page, aft_page, after_page = get_prev_after_pages_count(
        page, no_pages)

    return render(request, 'log_detail.html', {'profile_logs': profile_logs,
                                               'profile_log_records': profile_log_records,
                                               'profile_log': profile_log,
                                               'aft_page': aft_page,
                                               'after_page': after_page,
                                               'prev_page': prev_page,
                                               'previous_page': previous_page,
                                               'current_page': page,
                                               'last_page': no_pages,
                                               'no_of_jobs': no_of_jobs,
                                               })


def device_records_list(request):
    profile_logs = ProfileLog.objects.filter().order_by('-start_time')
    profile_logs_records = ProfileLogRecord.objects.filter(
        device__isnull=False).order_by('-timestamp')
    if request.POST.get("search"):
        profile_logs_records = profile_logs_records.filter(Q(request_path__icontains=request.POST.get(
            "search")) | Q(ip_address__icontains=request.POST.get("search")))
    if request.POST.get("queries"):
        profile_logs_records = profile_logs_records.filter(Q(sql_queries__lte=request.POST.get(
            "queries")) | Q(timer_utime__lte=request.POST.get("queries")))

    no_of_jobs = profile_logs_records.count()
    items_per_page = 10
    no_pages = int(math.ceil(float(no_of_jobs) / items_per_page))
    page = request.POST.get('page')
    if request.method == 'GET':
        page = request.GET.get('page')
    try:
        if int(page) > 0:
            if int(page) > (no_pages + 2):
                page = 1
            else:
                page = int(page)
        else:
            page = 1
    except:
        page = 1

    profile_logs_records = profile_logs_records[
        (page - 1) * items_per_page:page * items_per_page]
    prev_page, previous_page, aft_page, after_page = get_prev_after_pages_count(
        page, no_pages)

    return render(request, 'device_log_detail.html', {'profile_logs_records': profile_logs_records,
                                                      'profile_logs': profile_logs,
                                                      'aft_page': aft_page,
                                                      'after_page': after_page,
                                                      'prev_page': prev_page,
                                                      'previous_page': previous_page,
                                                      'current_page': page,
                                                      'last_page': no_pages,
                                                      'no_of_jobs': no_of_jobs,
                                                      })

django_web_profiler/templates/device_log_detail.html
{% extends 'profiler_base.html' %}
{% load profile_tags %}
{% block stage %}
<div class="col-sm-10">
  <div class="content">
    <div class="list">
      <div class="list-header">
        <label></label>
      </div>
      <div class="results-slct-items row mt">
        <form name="companyform" id="companyform" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-offset-2 col-md-10 search_form">
              <div class="col-md-4">
                <input type="text" class="form-control" placeholder="Search for path, ip address" name="search" id="search" value="{{request.POST.search}}">
              </div>
              <div class="row">
                <div class="col-md-4">
                  <input type="text" class="form-control" placeholder="Search for queries, cpu time" name="queries" id="queries" value="{{request.POST.queries}}">
                  <input type="hidden" name="page" id="page" value="{{request.POST.page}}">
                </div>
                <div class="col-md-2">
                  <button type="submit" class="form-control submit">Search</button>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
        </form>
        {% if profile_logs_records %}
        <table class="item_table table table-hover table-bordered" id="example_item">
          <thead>
            <tr>
              <th>#</th>
              <th>Path</th>
              <th>User Cpu Time</th>
              <th>System Cpu Time</th>
              <th>Ip Address</th>
            </tr>
          </thead>
          <tbody class="overflow:scroll;">
            {% for record in profile_logs_records %}
            <tr class="">
              <td class="item_details_control active" item_id="{{ record.id }}"><a class="open_table" href="#"><i class="fa fa-plus-circle"></i></a></td>
              <td>{{ record.request_path }}</td>
              <td>{{ record.timer_utime }}</td>
              <td>{{ record.timer_stime }}</td>
              <td>{{ record.ip_address }}</td>
            </tr>
            <tr class="sub_item_block sub_item_{{ record.id }}">
              <td colspan="8">
                <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                  <thead>
                    <tr>
                      <th>Device</th>
                      <th>Number of queries</th>
                      <th>Sql Time</th>
                      <th>No of cache calls</th>
                      <th>Cahe Time</th>
                      <th>Cache Hits</th>
                      <th>Cache Misses</th>
                      <th>Cache Sets</th>
                      <th>Cache Gets</th>
                    </tr>
                  </thead>
                  <tbody class="overflow:scroll;">
                    <tr class="sub_item_trs sub_item_{{ record.id }}">
                      <td>{% if record.device %}{{ record.device }}{% else %}None{% endif %}</td>
                      <td>{{ record.sql_queries }}</td>
                      <td>{{ record.sql_time }}</td>
                      <td>{% if record.cache_num_calls %}{{ record.cache_num_calls }}{% else %}None{% endif %}</td>
                      <td>{{ record.cache_time }}</td>
                      <td>{{ record.cache_hits }}</td>
                      <td>{{ record.cache_misses }}</td>
                      <th>{{ record.cache_sets }}</th>
                      <th>{{record.cache_gets}}</th>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        No Items Available in database
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="pagination_wrap text-center">
  {% get_page current_page last_page as pages %}
  <nav>
    <ul class="pagination">
      {% if current_page != 1 %}
      <li class="prev"><a href="#" class="{{previous_page}}"><i class="fa fa-angle-double-left"></i></a></li>
      <li class="prev"><a href="#" class="{{prev_page}}"><i class="fa fa-angle-left"></i></a></li>
      <li><a href="#" class="1">first</a></li>
      {% endif %}
      {% for s in pages %}
      <li {% ifequal s current_page %} class="active" {% endifequal %}><a href="#" class="{{s}}">{{s}}</a></li>
      {% endfor %}
      {% if current_page != last_page %}
      <li><a href="{{last_page}}" class="{{ last_page }}">last</a></li>
      <li><a href="#" class="{{ aft_page }}"><i class="fa fa-angle-right pagination-next"></i></a></li>
      <li><a href="#" class="{{ after_page }}"><i class="fa fa-angle-double-right"></i></a></li>
      {% endif %}
    </ul>
  </nav>
</div>
</div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.pagination li a').click(function(e) {
    e.preventDefault();
    $('#page').val($(this).attr('class'))
    url = '/profiler/device-records-list/';
    $('#companyform').attr('action', url)
    $('#companyform').submit();
  });

</script>
<script type="text/javascript">
  var table = $('#example').DataTable({"pageLength": 100,});

    $('.item_details_control').click(function(e){
      e.preventDefault();
    var record_id = $(this).attr('item_id')
            var tr = $(this).closest('tr');
        console.log($(tr).attr('class'))
        var row = table.row( tr );

        if ( $('tr.sub_item_'+record_id).hasClass('sub_item_block') ) {
            // This row is already open - close it
              row.child( $('tr.sub_item_'+record_id) ).show();
              tr.addClass('shown');
              $('tr.sub_item_'+record_id).removeClass('sub_item_block');

        }
        else {
            $('tr.sub_item_'+record_id).addClass('sub_item_block');
            tr.removeClass('shown');
            }

    if($(this).children().children('i').hasClass('fa fa-plus-circle')){
          $(this).children().children('i').removeClass('fa fa-plus-circle').addClass('fa fa-minus-circle');
      }
    else{
      $(this).children().children('i').removeClass('fa fa-minus-circle').addClass('fa fa-plus-circle');
    }
  });
</script>
{% endblock %}

django_web_profiler/templates/log_detail.html
{% extends 'profiler_base.html' %}
{% load profile_tags %}
{% block stage %}
<div class="col-sm-10">
  <div class="content">
    <div class="list">
      <div class="list-header">
        <label></label>
      </div>
      <div class="results-slct-items row mt">
        <form name="companyform" id="companyform" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-offset-2 col-md-10 search_form">
              <div class="col-md-4">
                <input type="text" class="form-control" placeholder="Search for path, ip address" name="search" id="search" value="{{request.POST.search}}">
              </div>
              <div class="row">
                <div class="col-md-4">
                  <input type="text" class="form-control" placeholder="Search for queries, cpu time" name="queries" id="queries" value="{{request.POST.queries}}">
                  <input type="hidden" name="page" id="page" value="{{request.POST.page}}">
                </div>
                <div class="col-md-2">
                  <button type="submit" class="form-control submit">Search</button>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
        </form>
        {% if profile_log_records %}
        <table class="item_table table table-hover table-bordered" id="example_item">
          <thead>
            <tr>
              <th>#</th>
              <th>Path</th>
              <th>User Cpu Time</th>
              <th>System Cpu Time</th>
              <th>Ip Address</th>
            </tr>
          </thead>
          <tbody class="overflow:scroll;">
            {% for record in profile_log_records %}
            <tr class="">
              <td class="item_details_control active" item_id="{{ record.id }}"><a class="open_table" href="#"><i class="fa fa-plus-circle"></i></a></td>
              <td>{{ record.request_path }}</td>
              <td>{{ record.timer_utime }}</td>
              <td>{{ record.timer_stime }}</td>
              <td>{{ record.ip_address }}</td>
            </tr>
            <tr class="sub_item_block sub_item_{{ record.id }}">
              <td colspan="8">
                <table style="overflow:scroll;" class="sub_items table table-hover table-bordered">
                  <thead>
                    <tr>
                      <th>Device</th>
                      <th>Number of queries</th>
                      <th>Sql Time</th>
                      <th>No of cache calls</th>
                      <th>Cahe Time</th>
                      <th>Cache Hits</th>
                      <th>Cache Misses</th>
                      <th>Cache Sets</th>
                      <th>Cache Gets</th>
                    </tr>
                  </thead>
                  <tbody class="overflow:scroll;">
                    <tr class="sub_item_trs sub_item_{{ record.id }}">
                      <td>{% if record.device %}{{ record.device }}{% else %}None{% endif %}</td>
                      <td>{{ record.sql_queries }}</td>
                      <td>{{ record.sql_time }}</td>
                      <td>{% if record.cache_num_calls %}{{ record.cache_num_calls }}{% else %}None{% endif %}</td>
                      <td>{{ record.cache_time }}</td>
                      <td>{{ record.cache_hits }}</td>
                      <td>{{ record.cache_misses }}</td>
                      <th>{{ record.cache_sets }}</th>
                      <th>{{record.cache_gets}}</th>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        No Items Available in database
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="pagination_wrap text-center">
  {% get_page current_page last_page as pages %}
  <nav>
    <ul class="pagination">
      {% if current_page != 1 %}
      <li class="prev"><a href="#" class="{{previous_page}}"><i class="fa fa-angle-double-left"></i></a></li>
      <li class="prev"><a href="#" class="{{prev_page}}"><i class="fa fa-angle-left"></i></a></li>
      <li><a href="#" class="1">first</a></li>
      {% endif %}
      {% for s in pages %}
      <li {% ifequal s current_page %} class="active" {% endifequal %}><a href="#" class="{{s}}">{{s}}</a></li>
      {% endfor %}
      {% if current_page != last_page %}
      <li><a href="{{last_page}}" class="{{ last_page }}">last</a></li>
      <li><a href="#" class="{{ aft_page }}"><i class="fa fa-angle-right pagination-next"></i></a></li>
      <li><a href="#" class="{{ after_page }}"><i class="fa fa-angle-double-right"></i></a></li>
      {% endif %}
    </ul>
  </nav>
</div>
</div>
</div>
{% endblock %}
{% block extra_js %}
<script type="text/javascript">
  $('.pagination li a').click(function(e) {
    e.preventDefault();
    $('#page').val($(this).attr('class'))
    url = '/profiler/device-records-list/';
    $('#companyform').attr('action', url)
    $('#companyform').submit();
  });

</script>
<script type="text/javascript">
  var table = $('#example').DataTable({"pageLength": 100,});

    $('.item_details_control').click(function(e){
      e.preventDefault();
    var record_id = $(this).attr('item_id')
            var tr = $(this).closest('tr');
        console.log($(tr).attr('class'))
        var row = table.row( tr );

        if ( $('tr.sub_item_'+record_id).hasClass('sub_item_block') ) {
            // This row is already open - close it
              row.child( $('tr.sub_item_'+record_id) ).show();
              tr.addClass('shown');
              $('tr.sub_item_'+record_id).removeClass('sub_item_block');
        }
        else {
            $('tr.sub_item_'+record_id).addClass('sub_item_block');
            tr.removeClass('shown');
            }
    if($(this).children().children('i').hasClass('fa fa-plus-circle')){
          $(this).children().children('i').removeClass('fa fa-plus-circle').addClass('fa fa-minus-circle');
      }
    else{
      $(this).children().children('i').removeClass('fa fa-minus-circle').addClass('fa fa-plus-circle');
    }
  });
</script>
{% endblock %}

django_web_profiler/templates/profiler_base.html
<!DOCTYPE html>
{% load static %}
{% load compress %}
<html lang="en">
<head>
  <title>Django Web Profiler</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  {% compress css %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/profiler_dashboard.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}" />
  {% endcompress %}

</head>
<body>

<div class="container-fluid">
  <div class="row marl content">
    <div class="col-sm-2 sidenav">
      <h4>Django Web Profiler</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><a href="{% url "django_web_profiler:device_records_list" %}">Device logs</a></li>

        {% for log in profile_logs %}
        <li><a href="{% url "django_web_profiler:records_list" log.id %}">{{log.name}}</a></li>
        {% endfor %}
      </ul><br>
    </div>
    {% block stage %}
    {% endblock %}
  </div>
</div>
  {% compress js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
  {% endcompress %}
    {% block extra_js %}
    {% endblock %}

</body>
</html>